apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s --secrets-as-files --build local -v
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: core-service
    app: kptmtools
    type: back-end
  name: core-service
spec:
  template:
    metadata:
      name: core-service-pod
      labels:
        app: kptmtools
        type: back-end
    spec:
      containers:
        - name: core-service-container
          image: ghcr.io/kptm-tools/core_service:dev
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8000/healthcheck"
          tty: true
      restartPolicy: Always
  replicas: 2
  selector:
    matchLabels: 
      type: back-end
