apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s --secrets-as-files --build local -v
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: core-service
  name: core-service
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: core-service
